name: base_library
description: Flutter基础类库
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6
  logger: ^0.8.3
  dio: ^3.0.8
  synchronized: ^2.2.0
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
